import type { FormField, FormFieldBody, FormSchema, FormSchemaBody } from '#shared/types/models'
import { ulid } from './ulid'

/** The rules the builder has controls for; anything else stays in `custom`, unchanged. */
export interface RuleState {
  required: boolean
  email: boolean
  numeric: boolean
  url: boolean
  /** `min:N` / `max:N`, as typed (empty when not set). */
  min: string
  max: string
  /** `in:a,b,c` values. */
  oneOf: string[]
  custom: string[]
}

export interface FieldDraft extends RuleState {
  /** Stable key for rendering and errors; not saved. */
  key: string
  /** The field's `id`: a ULID, generated by the builder and never edited. */
  id: string
  label: string
  /** The `name` the site's input uses, and the key submitted values are stored under. */
  name: string
  /** Whether the input name was typed, so it stops following the label. */
  nameEdited: boolean
}

export type DraftErrors = Record<string, Partial<Record<'name' | 'min' | 'max', string>>>

/** Input names start with a letter, then letters, digits, `_` or `-`. */
export const inputNamePattern = /^[A-Za-z][A-Za-z0-9_-]*$/

const integerPattern = /^\d+$/

let draftCounter = 0

export function newDraftKey() {
  draftCounter += 1

  return `field-${draftCounter}`
}

/** A new, empty row with a fresh ULID. */
export function newFieldDraft(): FieldDraft {
  return {
    key: newDraftKey(),
    id: ulid(),
    label: '',
    name: '',
    nameEdited: false,
    ...parseRules(undefined),
  }
}

/** Splits rules the way the API does: arrays as they are, strings on commas. */
export function splitRules(rules: FormField['rules']): string[] {
  const list = Array.isArray(rules) ? rules : typeof rules === 'string' ? rules.split(',') : []

  return list.map((rule) => rule.trim()).filter(Boolean)
}

export function parseRules(rules: FormField['rules']): RuleState {
  const state: RuleState = {
    required: false,
    email: false,
    numeric: false,
    url: false,
    min: '',
    max: '',
    oneOf: [],
    custom: [],
  }

  for (const rule of splitRules(rules)) {
    if (rule === 'required' || rule === 'email' || rule === 'numeric' || rule === 'url') {
      state[rule] = true
    } else if (/^min:\d+$/.test(rule) && !state.min) {
      state.min = rule.slice(4)
    } else if (/^max:\d+$/.test(rule) && !state.max) {
      state.max = rule.slice(4)
    } else if (rule.startsWith('in:') && state.oneOf.length === 0) {
      state.oneOf = rule.slice(3).split(',').filter(Boolean)
    } else {
      state.custom.push(rule)
    }
  }

  return state
}

export function serializeRules(state: RuleState): string[] {
  const rules: string[] = []

  if (state.required) rules.push('required')
  if (state.email) rules.push('email')
  if (state.numeric) rules.push('numeric')
  if (state.url) rules.push('url')
  if (state.min.trim()) rules.push(`min:${state.min.trim()}`)
  if (state.max.trim()) rules.push(`max:${state.max.trim()}`)

  const oneOf = state.oneOf.map((value) => value.trim()).filter(Boolean)

  if (oneOf.length > 0) rules.push(`in:${oneOf.join(',')}`)

  return [...rules, ...state.custom.map((rule) => rule.trim()).filter(Boolean)]
}

/** Sorts a schema's fields by `order`. The API already returns them sorted; this keeps ties stable. */
export function orderedFields(schema: FormSchema | null | undefined): FormField[] {
  return [...(schema ?? [])].sort((a, b) => a.order - b.order)
}

/**
 * Reads a form's schema into editable rows, sorted by `order`. A field without a `name` keeps its
 * ID as its input name, so the site's form, existing entries and exports carry on working.
 */
export function schemaToDrafts(schema: FormSchema | null | undefined): FieldDraft[] {
  return orderedFields(schema).map((field) => ({
    key: newDraftKey(),
    id: field.id,
    label: field.label ?? '',
    name: field.name || field.id,
    nameEdited: true,
    ...parseRules(field.rules),
  }))
}

/** Builds the `schema` to save: one field per row, `order` numbered from 1, leaving out empty labels and rules. */
export function draftsToSchema(drafts: readonly FieldDraft[]): FormSchemaBody {
  return drafts.map((draft, index) => {
    const field: FormFieldBody = { id: draft.id, order: index + 1 }
    const label = draft.label.trim()
    const name = draft.name.trim()
    const rules = serializeRules(draft)

    if (label) field.label = label
    // A name equal to the ID is the API's default, so it's left out.
    if (name && name !== draft.id) field.name = name
    if (rules.length > 0) field.rules = rules

    return field
  })
}

/** The name the site's input must use. */
export function inputName(draft: Pick<FieldDraft, 'id' | 'name'>): string {
  return draft.name.trim() || draft.id
}

/** `Email address` → `email_address`; input names always start with a letter. */
export function slugifyInputName(label: string): string {
  const slug = label
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 64)

  if (!slug) {
    return ''
  }

  return /^[a-z]/.test(slug) ? slug : `field_${slug}`
}

export function validateDrafts(drafts: readonly FieldDraft[]): DraftErrors {
  const errors: DraftErrors = {}
  const names = new Map<string, number>()

  for (const draft of drafts) {
    names.set(inputName(draft), (names.get(inputName(draft)) ?? 0) + 1)
  }

  for (const draft of drafts) {
    const fieldErrors: DraftErrors[string] = {}
    const name = draft.name.trim()

    if (!name) {
      fieldErrors.name = 'Give the field an input name.'
    } else if (name !== draft.id && !inputNamePattern.test(name)) {
      fieldErrors.name = 'Start with a letter, then use letters, digits, “_” or “-”.'
    } else if ((names.get(name) ?? 0) > 1) {
      fieldErrors.name = 'Another field already uses this input name.'
    }

    if (draft.min.trim() && !integerPattern.test(draft.min.trim())) {
      fieldErrors.min = 'Use a whole number.'
    }

    if (draft.max.trim() && !integerPattern.test(draft.max.trim())) {
      fieldErrors.max = 'Use a whole number.'
    }

    if (Object.keys(fieldErrors).length > 0) {
      errors[draft.key] = fieldErrors
    }
  }

  return errors
}
