/**
 * Generated by scripts/generate-api-types.mjs from http://localhost:8001/docs/api.json. Do not edit by hand.
 */

export interface paths {
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user */
        get: operations["auth.me"];
        put?: never;
        post?: never;
        /** Permanently delete the account and everything it owns */
        delete: operations["auth.me.destroy"];
        options?: never;
        head?: never;
        /** Update the authenticated user's name or email. Changing the email clears its verification */
        patch: operations["auth.me.update"];
        trace?: never;
    };
    "/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the password, revoke every existing token, and return a new one for this client */
        put: operations["auth.password.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange an email and password for an access token */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a current or recently expired token for a new one
         * @description The old token is blacklisted. Refreshing is allowed until the
         *     token is older than the configured refresh TTL, and never for a
         *     token revoked by a password change or reset: the new token keeps
         *     the original token version, so it is checked against revocation.
         */
        post: operations["auth.refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate the current token */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["forms.index"];
        put?: never;
        post: operations["forms.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["forms.show"];
        put: operations["forms.update"];
        post?: never;
        delete: operations["forms.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forms.restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy a form's name, schema, and settings into a new, inactive form */
        post: operations["forms.duplicate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form}/entries/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forms.entries.bulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["forms.entries.index"];
        put?: never;
        post: operations["forms.entries.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{entry}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["entries.show"];
        put: operations["entries.update"];
        post?: never;
        delete: operations["entries.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{entry}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["entries.restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{entry}/force": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["entries.force-destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entry-exports/{export}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a completed export's CSV
         * @description Reached through the temporary signed `download_url` from an export response, not the API token:
         *     the signature shows the link was issued to a user allowed to view the export. A missing, altered
         *     or expired signature returns 403.
         */
        get: operations["entry-exports.download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form}/entries/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a CSV export of the form's entries, using the same filters and sort as the entry index */
        post: operations["forms.entries.exports.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entry-exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the exports of the user's forms, newest first, with their status
         * @description Exports past their `expires_at` are left out, as are exports of deleted forms.
         */
        get: operations["entry-exports.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entry-exports/{export}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["entry-exports.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["forms.notifications.index"];
        put?: never;
        post: operations["forms.notifications.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{notification}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notifications.show"];
        put: operations["notifications.update"];
        post?: never;
        delete: operations["notifications.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{notification}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["notifications.restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a public, unauthenticated submission to a form
         * @description The body fields are the form's schema input names (each field's `name`, or its ID), validated with
         *     the field's rules. Unknown fields are dropped.
         *
         *     Responds with the form's `redirect` and `message` settings so the client can show the
         *     success message or navigate to the redirect itself; no 3XX redirect is ever sent.
         *
         *     A submission that fills in the form's honeypot field gets the same response, so bots cannot
         *     tell, but is stored flagged as spam. Other submissions are checked for spam before the form's
         *     recipients are alerted.
         */
        post: operations["forms.submissions.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a password reset link. The response is the same whether or not the account exists, or
         *     the request was throttled, so the endpoint cannot be used to discover registered emails
         */
        post: operations["auth.forgot-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password from an emailed reset token and revoke every existing token */
        post: operations["auth.reset-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/postmark/bounces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a bounce or spam complaint for an alert email on the recipient it was sent to, identified by
         *     the recipient ID carried in the message metadata. Anything else, or a message this service did not
         *     tag, is acknowledged and ignored so Postmark does not retry it
         */
        post: operations["webhooks.postmark.bounces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        /** FormCollection */
        FormCollection: {
            data: components["schemas"]["FormResource"][];
        };
        /** FormEntryBulkRequest */
        FormEntryBulkRequest: {
            /** @enum {string} */
            action: "mark_read" | "mark_unread" | "star" | "unstar" | "mark_spam" | "mark_not_spam" | "delete" | "restore" | "force_delete";
            ids: string[];
        };
        /** FormEntryCollection */
        FormEntryCollection: {
            data: components["schemas"]["FormEntryResource"][];
        };
        /** FormEntryExportCollection */
        FormEntryExportCollection: {
            data: components["schemas"]["FormEntryExportResource"][];
        };
        /** FormEntryExportResource */
        FormEntryExportResource: {
            id: string;
            form_id: string;
            status: string;
            /** @description The entry filters and sort the export was created with. */
            parameters: {
                sort?: string;
                filter?: {
                    [key: string]: string;
                };
            };
            filename: string;
            row_count: number | null;
            error: string | null;
            /**
             * @description A temporary signed link to the CSV, usable without the API token, e.g. as a plain browser
             *     link. It expires a few minutes after this response (see `EXPORT_DOWNLOAD_URL_TTL`), so
             *     fetch the export again for a fresh link. `null` until the export is completed.
             */
            download_url: string | null;
            /** Format: date-time */
            completed_at: string | null;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** FormEntryIndexRequest */
        FormEntryIndexRequest: {
            /** @description Results per page, from 1 to 100. Defaults to 15. Ignored when requesting an export. */
            per_page?: number;
            /** @enum {string} */
            sort?: "created_at" | "-created_at" | "spam_score" | "-spam_score";
            /** @description Every filter is optional. Unknown keys are rejected. */
            filter?: {
                /** @enum {string} */
                read?: "true" | "false" | "1" | "0";
                /** @enum {string} */
                starred?: "true" | "false" | "1" | "0";
                /** @enum {string} */
                spam?: "true" | "false" | "1" | "0";
                /** Format: date */
                created_from?: string;
                /** Format: date */
                created_to?: string;
                /** @enum {string} */
                trashed?: "with" | "only";
            };
        };
        /** FormEntryResource */
        FormEntryResource: {
            id: string;
            form_id: string;
            input: {
                [key: string]: unknown;
            } | null;
            ip: string | null;
            ip_location_display: string | null;
            referer: string | null;
            user_agent: string | null;
            user_agent_display: {
                platform: string | null;
                browser: string | null;
                browser_version: string | null;
            } | null;
            spam: boolean | null;
            /** @description Spam likelihood from 0 (not spam) to 1 (spam), to three decimal places. */
            spam_score: number;
            spam_reason: string | null;
            /**
             * Format: date-time
             * @description When the entry's spam check finished: when it was created for honeypot hits and entries
             *     created through the API, or when Jev classified a public submission. `null` while a
             *     submission awaits classification, or if classification was unavailable.
             */
            spam_checked_at: string | null;
            starred: boolean;
            /** Format: date-time */
            read_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            /** Format: date-time */
            deleted_at: string | null;
        };
        /** FormEntryUpdateRequest */
        FormEntryUpdateRequest: {
            /** @description Recorded at submission time. Rejected if sent. */
            input?: {
                [key: string]: unknown;
            } | null;
            ip?: string;
            ip_location_display?: string;
            referer?: string;
            user_agent?: string;
            /** @description Recorded at submission time. Rejected if sent. */
            user_agent_display?: {
                platform: string | null;
                browser: string | null;
                browser_version: string | null;
            } | null;
            /** @description Recorded by the spam check. Rejected if sent. */
            spam_checked_at?: string;
            spam?: boolean | null;
            spam_score?: number;
            spam_reason?: string | null;
            starred?: boolean;
            /** Format: date-time */
            read_at?: string | null;
        };
        /** FormNotificationCollection */
        FormNotificationCollection: {
            data: components["schemas"]["FormNotificationResource"][];
        };
        /** FormNotificationResource */
        FormNotificationResource: {
            id: string;
            form_id: string;
            type: string;
            value: string;
            enabled: boolean;
            error: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            /** Format: date-time */
            deleted_at: string | null;
        };
        /** FormNotificationStoreRequest */
        FormNotificationStoreRequest: {
            /** @enum {string} */
            type: "email" | "sms";
            value: string;
            enabled?: boolean;
            error?: string;
        };
        /** FormNotificationUpdateRequest */
        FormNotificationUpdateRequest: {
            form_id?: string;
            /** @enum {string} */
            type: "email" | "sms";
            value: string;
            enabled: boolean;
            error?: string;
        };
        /** FormResource */
        FormResource: {
            id: string;
            user_id: number;
            name: string;
            active: boolean;
            /** @description Fields sorted by `order`. */
            schema: {
                id: string;
                order: number;
                label?: string;
                name?: string;
                rules?: string[] | string;
            }[] | null;
            settings: {
                redirect: string | null;
                timezone: string | null;
                domains: string[] | null;
                message: string | null;
                honeypot_enabled: boolean;
                honeypot_name: string | null;
            } | null;
            /** @description Entries on the form, excluding spam and deleted ones. Included in the form list only. */
            entries_count?: number;
            /** @description Entries on the form not yet marked read, excluding spam and deleted ones. Included in the form list only. */
            unread_entries_count?: number;
            /** @description Entries on the form marked as spam, excluding deleted ones. Included in the form list only. */
            spam_entries_count?: number;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            /** Format: date-time */
            deleted_at: string | null;
        };
        /** FormSettings */
        FormSettings: {
            [key: string]: unknown;
        };
        /** FormStoreRequest */
        FormStoreRequest: {
            name: string;
            /**
             * @description A list of fields. Each has a unique ULID `id` and an integer `order` used to sort fields for
             *     display, and may set a `label`, an input `name` (defaults to the ID) and Laravel validation
             *     `rules` (an array or a comma-separated string). Other keys are rejected.
             */
            schema?: {
                id: string;
                order: number;
                label?: string | null;
                name?: string | null;
                rules?: string[] | null;
            }[] | null;
            /** @description Every key is optional and takes its default when omitted. Unknown keys are rejected. */
            settings?: {
                redirect?: string | null;
                timezone?: string | null;
                domains?: string[] | null;
                message?: string | null;
                honeypot_enabled?: boolean;
                honeypot_name?: string | null;
            } | null;
        };
        /** FormUpdateRequest */
        FormUpdateRequest: {
            name: string;
            active: boolean;
            /**
             * @description A list of fields. Each has a unique ULID `id` and an integer `order` used to sort fields for
             *     display, and may set a `label`, an input `name` (defaults to the ID) and Laravel validation
             *     `rules` (an array or a comma-separated string). Other keys are rejected.
             */
            schema?: {
                id: string;
                order: number;
                label?: string | null;
                name?: string | null;
                rules?: string[] | null;
            }[] | null;
            /** @description Every key is optional and takes its default when omitted. Unknown keys are rejected. */
            settings?: {
                redirect?: string | null;
                timezone?: string | null;
                domains?: string[] | null;
                message?: string | null;
                honeypot_enabled?: boolean;
                honeypot_name?: string | null;
            } | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            token: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirmation: string;
        };
        /** UpdatePasswordRequest */
        UpdatePasswordRequest: {
            current_password: string;
            password: string;
            password_confirmation: string;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            name?: string;
            /** Format: email */
            email?: string;
        };
        /** UserResource */
        UserResource: {
            id: number;
            name: string;
            email: string;
            /** Format: date-time */
            email_verified_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.me.destroy": {
        parameters: {
            query: {
                password: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.me.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.password.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token: string;
                        /** @constant */
                        token_type: "bearer";
                        expires_in: number;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token: string;
                        /** @constant */
                        token_type: "bearer";
                        expires_in: number;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token: string;
                        /** @constant */
                        token_type: "bearer";
                        expires_in: number;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "forms.index": {
        parameters: {
            query?: {
                /** @description Results per page, from 1 to 100. Defaults to 15. */
                per_page?: number;
                sort?: "created_at" | "-created_at" | "updated_at" | "-updated_at" | "name" | "-name";
                "filter[active]"?: "true" | "false" | "1" | "0";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `FormResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormCollection"] & {
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "forms.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormStoreRequest"];
            };
        };
        responses: {
            /** @description `FormResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "forms.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `FormResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "forms.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormUpdateRequest"];
            };
        };
        responses: {
            /** @description `FormResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "forms.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "forms.restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `FormResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "forms.duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `FormResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "forms.entries.bulk": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormEntryBulkRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            action: unknown;
                            affected: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "forms.entries.index": {
        parameters: {
            query?: {
                /** @description Results per page, from 1 to 100. Defaults to 15. Ignored when requesting an export. */
                per_page?: number;
                sort?: "created_at" | "-created_at" | "spam_score" | "-spam_score";
                "filter[read]"?: "true" | "false" | "1" | "0";
                "filter[starred]"?: "true" | "false" | "1" | "0";
                "filter[spam]"?: "true" | "false" | "1" | "0";
                "filter[created_from]"?: string;
                "filter[created_to]"?: string;
                "filter[trashed]"?: "with" | "only";
            };
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `FormEntryResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormEntryCollection"] & {
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "forms.entries.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `FormEntryResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormEntryResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "entries.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry ID */
                entry: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `FormEntryResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormEntryResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "entries.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry ID */
                entry: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FormEntryUpdateRequest"];
            };
        };
        responses: {
            /** @description `FormEntryResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormEntryResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "entries.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry ID */
                entry: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "entries.restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry ID */
                entry: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `FormEntryResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormEntryResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "entries.force-destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry ID */
                entry: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "entry-exports.download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The export ID */
                export: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    "Transfer-Encoding": "chunked";
                    [name: string]: unknown;
                };
                content: {
                    "text/csv; charset=UTF-8": string;
                };
            };
            /** @description Missing, invalid or expired signature */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            /** @description An error */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example This export is not ready.
                         */
                        message: string;
                    };
                };
            };
            /** @description An error */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example This export has expired.
                         */
                        message: string;
                    };
                };
            };
        };
    };
    "forms.entries.exports.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FormEntryIndexRequest"];
            };
        };
        responses: {
            /** @description `FormEntryExportResource` */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormEntryExportResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "entry-exports.index": {
        parameters: {
            query?: {
                /** @description Results per page, from 1 to 100. Defaults to 15. */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `FormEntryExportResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormEntryExportCollection"] & {
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "entry-exports.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The export ID */
                export: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `FormEntryExportResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormEntryExportResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "forms.notifications.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `FormNotificationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormNotificationCollection"] & {
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "forms.notifications.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormNotificationStoreRequest"];
            };
        };
        responses: {
            /** @description `FormNotificationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormNotificationResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "notifications.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The notification ID */
                notification: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `FormNotificationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormNotificationResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "notifications.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The notification ID */
                notification: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormNotificationUpdateRequest"];
            };
        };
        responses: {
            /** @description `FormNotificationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormNotificationResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "notifications.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The notification ID */
                notification: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "notifications.restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The notification ID */
                notification: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `FormNotificationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormNotificationResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "forms.submissions.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The form ID */
                form: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            redirect: string | null;
                            message: string | null;
                        };
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "If an account exists for that email, a password reset link has been sent.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: unknown;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "webhooks.postmark.bounces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    RecordType?: string;
                    Description?: string;
                };
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
